### ISSUE TITLE
Needs more code

### ISSUE THREAD

**Issue by dylanwatsonsoftware** [zeroreign/conferences#1]
😜

**Comment by zeroreign** [comment]
Haha yeah. Need more workshops. But atm might need a readme for the ones that provide you free accounts.

**Comment by zeroreign** [comment]
Updated readme with new intent on the repo now that I know workshops give you an environment that's already set up.
This is going to turn more into a journal of notes from conferences and links to talks.

**Comment by dylanwatsonsoftware** [comment]
I literally always assumed that was your plan 😂
